# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

orderMatrixCPP <- function(x, sortDirection, k = 5L) {
    .Call('_CaseBasedReasoning_orderMatrixCPP', PACKAGE = 'CaseBasedReasoning', x, sortDirection, k)
}

orderVectorCPP <- function(x, sortDirection, k = 0L) {
    .Call('_CaseBasedReasoning_orderVectorCPP', PACKAGE = 'CaseBasedReasoning', x, sortDirection, k)
}

terminalNodeIDRanger <- function(x, childNodes1, childNodes2, splitValues, splitVarIds) {
    .Call('_CaseBasedReasoning_terminalNodeIDRanger', PACKAGE = 'CaseBasedReasoning', x, childNodes1, childNodes2, splitValues, splitVarIds)
}

