# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_Matrix_Order <- function(mDist, nCases) {
    .Call('cbr_fast_Matrix_Order', PACKAGE = 'cbr', mDist, nCases)
}

fast_Vector_Order <- function(vX, n) {
    .Call('cbr_fast_Vector_Order', PACKAGE = 'cbr', vX, n)
}

get_Distance_Matrix <- function(newData, refData, weights) {
    .Call('cbr_get_Distance_Matrix', PACKAGE = 'cbr', newData, refData, weights)
}

get_nearest_Elements <- function(mNew, mRef, vWeights, nCases) {
    .Call('cbr_get_nearest_Elements', PACKAGE = 'cbr', mNew, mRef, vWeights, nCases)
}

