# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_parallelDistance <- function(dataList, attrs, arguments) {
    .Call('_CaseBasedReasoning_cpp_parallelDistance', PACKAGE = 'CaseBasedReasoning', dataList, attrs, arguments)
}

cpp_order_matrix <- function(x, sortDirection, k = 5L) {
    .Call('_CaseBasedReasoning_cpp_order_matrix', PACKAGE = 'CaseBasedReasoning', x, sortDirection, k)
}

cpp_order_vector <- function(x, sortDirection, k = 0L) {
    .Call('_CaseBasedReasoning_cpp_order_vector', PACKAGE = 'CaseBasedReasoning', x, sortDirection, k)
}

cpp_terminalNodeID <- function(x, childNodes1, childNodes2, splitValues, splitVarIds) {
    .Call('_CaseBasedReasoning_cpp_terminalNodeID', PACKAGE = 'CaseBasedReasoning', x, childNodes1, childNodes2, splitValues, splitVarIds)
}

cpp_TerminalNodeDistance <- function(nodeIDs) {
    .Call('_CaseBasedReasoning_cpp_TerminalNodeDistance', PACKAGE = 'CaseBasedReasoning', nodeIDs)
}

